on: 
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
    type: choice

jobs:
  pvpython-5_11_2:
    uses: ./.github/workflows/pvpython-testing.yml
    with:
      PARAVIEW_PATH: /imcs/public/compsim/opt/ParaView-5.11.2-osmesa-MPI-Linux-Python3.9-x86_64/

  system-python-5_11_2:
    uses: ./.github/workflows/python-testing.yml
    with:
      PARAVIEW_PATH: /imcs/public/compsim/opt/ParaView-5.11.2-osmesa-MPI-Linux-Python3.9-x86_64/
      SPACK_ACTIVATION_SCRIPT: /home_local/github-runner/testing_lib/spack/share/spack/setup-env.sh
      PARAVIEW_SITE_PACKAGES: "/lib/python3.9/site-packages"
      PARAVIEW_LIBRARY_PATH: "/lib"
  
  code-check:
    uses: ./.github/workflows/pvutils-code-check.yml
    with:
      SPACK_ACTIVATION_SCRIPT: /home_local/github-runner/testing_lib/spack/share/spack/setup-env.sh
      PYTHON_VENV: "env"
