name: pvutils-code-check

on: 
  workflow_call:
    inputs:
      SPACK_ACTIVATION_SCRIPT:
        required: true
        type: string
      PYTHON_VENV:
        required: true
        type: string

jobs:
  testing:
    name: pvutils-code-check
    runs-on: self-hosted
    env:
      SPACK_ACTIVATION_SCRIPT: ${{inputs.SPACK_ACTIVATION_SCRIPT}}
      PYTHON_VENV: ${{inputs.PYTHON_VENV}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Display user name
        run: "whoami"
      - name: Print the working directory
        run: "pwd"
      - name: Setup virtual environment, install black and run code check
        run: |
          . ${SPACK_ACTIVATION_SCRIPT}
          spack load python@3.9.15
          python3 -m venv $PYTHON_VENV
          source $PYTHON_VENV/bin/activate
          cd tests
          python3 testing_header.py
          cd ..
          pip install black
          black . --check --exclude="$PYTHON_VENV" && exit 0
          exit 1
